export enum UserRole {
  SUPER_ADMIN = "super_admin",
  CHAIRMAN = "chairman",
  CEO = "ceo",
  COO = "coo",
  CFO = "cfo",
  CTO = "cto",
  CCO = "cco",
  CIO = "cio",

  REGIONAL_DIRECTOR = "regional_director",
  BRANCH_MANAGER = "branch_manager",
  DEPUTY_BRANCH_MANAGER = "deputy_branch_manager",

  HEAD_OF_SALES = "head_of_sales",
  HEAD_OF_SERVICE = "head_of_service",
  HEAD_OF_INSTALLATION = "head_of_installation",
  HEAD_OF_FINANCE = "head_of_finance",
  HEAD_OF_COLLECTION = "head_of_collection",
  HEAD_OF_PROCUREMENT = "head_of_procurement",
  HEAD_OF_WAREHOUSE = "head_of_warehouse",
  HEAD_OF_HR = "head_of_hr",
  HEAD_OF_CUSTOMER_CARE = "head_of_customer_care",
  HEAD_OF_QUALITY = "head_of_quality",
  HEAD_OF_IT = "head_of_it",
  HEAD_OF_MARKETING = "head_of_marketing",

  SALES_MANAGER = "sales_manager",
  SERVICE_MANAGER = "service_manager",
  DISPATCH_MANAGER = "dispatch_manager",
  INSTALLATION_MANAGER = "installation_manager",
  FINANCE_MANAGER = "finance_manager",
  COLLECTION_MANAGER = "collection_manager",
  PROCUREMENT_MANAGER = "procurement_manager",
  WAREHOUSE_MANAGER = "warehouse_manager",
  HR_MANAGER = "hr_manager",
  CUSTOMER_CARE_MANAGER = "customer_care_manager",
  QUALITY_MANAGER = "quality_manager",
  IT_MANAGER = "it_manager",
  PROJECT_MANAGER = "project_manager",

  SALES_TEAM_LEADER = "sales_team_leader",
  SERVICE_SUPERVISOR = "service_supervisor",
  INSTALLATION_SUPERVISOR = "installation_supervisor",
  COLLECTION_SUPERVISOR = "collection_supervisor",
  ACCOUNTING_SUPERVISOR = "accounting_supervisor",

  SALES_EXECUTIVE = "sales_executive",
  SALES_ENGINEER = "sales_engineer",
  ACCOUNT_MANAGER = "account_manager",
  SERVICE_TECHNICIAN = "service_technician",
  SENIOR_TECHNICIAN = "senior_technician",
  INSTALLATION_TECHNICIAN = "installation_technician",
  APPRENTICE_TECHNICIAN = "apprentice_technician",
  ACCOUNTANT = "accountant",
  COLLECTION_OFFICER = "collection_officer",
  CASHIER = "cashier",
  PROCUREMENT_OFFICER = "procurement_officer",
  WAREHOUSE_OFFICER = "warehouse_officer",
  INVENTORY_CLERK = "inventory_clerk",
  CUSTOMER_CARE_AGENT = "customer_care_agent",
  DISPATCHER = "dispatcher",
  RECEPTIONIST = "receptionist",
  HR_OFFICER = "hr_officer",
  QA_INSPECTOR = "qa_inspector",
  SAFETY_OFFICER = "safety_officer",
  IT_SUPPORT = "it_support",
  DATA_ANALYST = "data_analyst",

  CUSTOMER = "customer",
}

export const ROLE_TIERS: Record<UserRole, number> = {
  [UserRole.SUPER_ADMIN]: 100,
  [UserRole.CHAIRMAN]: 95,
  [UserRole.CEO]: 90,
  [UserRole.COO]: 85,
  [UserRole.CFO]: 85,
  [UserRole.CTO]: 85,
  [UserRole.CCO]: 85,
  [UserRole.CIO]: 85,
  [UserRole.REGIONAL_DIRECTOR]: 80,
  [UserRole.BRANCH_MANAGER]: 75,
  [UserRole.DEPUTY_BRANCH_MANAGER]: 70,
  [UserRole.HEAD_OF_SALES]: 65,
  [UserRole.HEAD_OF_SERVICE]: 65,
  [UserRole.HEAD_OF_INSTALLATION]: 65,
  [UserRole.HEAD_OF_FINANCE]: 65,
  [UserRole.HEAD_OF_COLLECTION]: 65,
  [UserRole.HEAD_OF_PROCUREMENT]: 65,
  [UserRole.HEAD_OF_WAREHOUSE]: 65,
  [UserRole.HEAD_OF_HR]: 65,
  [UserRole.HEAD_OF_CUSTOMER_CARE]: 65,
  [UserRole.HEAD_OF_QUALITY]: 65,
  [UserRole.HEAD_OF_IT]: 65,
  [UserRole.HEAD_OF_MARKETING]: 65,
  [UserRole.SALES_MANAGER]: 55,
  [UserRole.SERVICE_MANAGER]: 55,
  [UserRole.DISPATCH_MANAGER]: 55,
  [UserRole.INSTALLATION_MANAGER]: 55,
  [UserRole.FINANCE_MANAGER]: 55,
  [UserRole.COLLECTION_MANAGER]: 55,
  [UserRole.PROCUREMENT_MANAGER]: 55,
  [UserRole.WAREHOUSE_MANAGER]: 55,
  [UserRole.HR_MANAGER]: 55,
  [UserRole.CUSTOMER_CARE_MANAGER]: 55,
  [UserRole.QUALITY_MANAGER]: 55,
  [UserRole.IT_MANAGER]: 55,
  [UserRole.PROJECT_MANAGER]: 55,
  [UserRole.SALES_TEAM_LEADER]: 45,
  [UserRole.SERVICE_SUPERVISOR]: 45,
  [UserRole.INSTALLATION_SUPERVISOR]: 45,
  [UserRole.COLLECTION_SUPERVISOR]: 45,
  [UserRole.ACCOUNTING_SUPERVISOR]: 45,
  [UserRole.SALES_EXECUTIVE]: 30,
  [UserRole.SALES_ENGINEER]: 30,
  [UserRole.ACCOUNT_MANAGER]: 30,
  [UserRole.SERVICE_TECHNICIAN]: 25,
  [UserRole.SENIOR_TECHNICIAN]: 30,
  [UserRole.INSTALLATION_TECHNICIAN]: 25,
  [UserRole.APPRENTICE_TECHNICIAN]: 15,
  [UserRole.ACCOUNTANT]: 25,
  [UserRole.COLLECTION_OFFICER]: 25,
  [UserRole.CASHIER]: 20,
  [UserRole.PROCUREMENT_OFFICER]: 25,
  [UserRole.WAREHOUSE_OFFICER]: 25,
  [UserRole.INVENTORY_CLERK]: 20,
  [UserRole.CUSTOMER_CARE_AGENT]: 25,
  [UserRole.DISPATCHER]: 30,
  [UserRole.RECEPTIONIST]: 20,
  [UserRole.HR_OFFICER]: 25,
  [UserRole.QA_INSPECTOR]: 30,
  [UserRole.SAFETY_OFFICER]: 30,
  [UserRole.IT_SUPPORT]: 25,
  [UserRole.DATA_ANALYST]: 30,
  [UserRole.CUSTOMER]: 0,
};

export const ROLE_LABELS: Record<UserRole, string> = {
  [UserRole.SUPER_ADMIN]: "Super Admin",
  [UserRole.CHAIRMAN]: "Chairman",
  [UserRole.CEO]: "Chief Executive Officer",
  [UserRole.COO]: "Chief Operating Officer",
  [UserRole.CFO]: "Chief Financial Officer",
  [UserRole.CTO]: "Chief Technology Officer",
  [UserRole.CCO]: "Chief Commercial Officer",
  [UserRole.CIO]: "Chief Information Officer",
  [UserRole.REGIONAL_DIRECTOR]: "Regional Director",
  [UserRole.BRANCH_MANAGER]: "Branch Manager",
  [UserRole.DEPUTY_BRANCH_MANAGER]: "Deputy Branch Manager",
  [UserRole.HEAD_OF_SALES]: "Head of Sales",
  [UserRole.HEAD_OF_SERVICE]: "Head of Service",
  [UserRole.HEAD_OF_INSTALLATION]: "Head of Installation",
  [UserRole.HEAD_OF_FINANCE]: "Head of Finance",
  [UserRole.HEAD_OF_COLLECTION]: "Head of Collection",
  [UserRole.HEAD_OF_PROCUREMENT]: "Head of Procurement",
  [UserRole.HEAD_OF_WAREHOUSE]: "Head of Warehouse",
  [UserRole.HEAD_OF_HR]: "Head of HR",
  [UserRole.HEAD_OF_CUSTOMER_CARE]: "Head of Customer Care",
  [UserRole.HEAD_OF_QUALITY]: "Head of Quality",
  [UserRole.HEAD_OF_IT]: "Head of IT",
  [UserRole.HEAD_OF_MARKETING]: "Head of Marketing",
  [UserRole.SALES_MANAGER]: "Sales Manager",
  [UserRole.SERVICE_MANAGER]: "Service Manager",
  [UserRole.DISPATCH_MANAGER]: "Dispatch Manager",
  [UserRole.INSTALLATION_MANAGER]: "Installation Manager",
  [UserRole.FINANCE_MANAGER]: "Finance Manager",
  [UserRole.COLLECTION_MANAGER]: "Collection Manager",
  [UserRole.PROCUREMENT_MANAGER]: "Procurement Manager",
  [UserRole.WAREHOUSE_MANAGER]: "Warehouse Manager",
  [UserRole.HR_MANAGER]: "HR Manager",
  [UserRole.CUSTOMER_CARE_MANAGER]: "Customer Care Manager",
  [UserRole.QUALITY_MANAGER]: "Quality Manager",
  [UserRole.IT_MANAGER]: "IT Manager",
  [UserRole.PROJECT_MANAGER]: "Project Manager",
  [UserRole.SALES_TEAM_LEADER]: "Sales Team Leader",
  [UserRole.SERVICE_SUPERVISOR]: "Service Supervisor",
  [UserRole.INSTALLATION_SUPERVISOR]: "Installation Supervisor",
  [UserRole.COLLECTION_SUPERVISOR]: "Collection Supervisor",
  [UserRole.ACCOUNTING_SUPERVISOR]: "Accounting Supervisor",
  [UserRole.SALES_EXECUTIVE]: "Sales Executive",
  [UserRole.SALES_ENGINEER]: "Sales Engineer",
  [UserRole.ACCOUNT_MANAGER]: "Account Manager",
  [UserRole.SERVICE_TECHNICIAN]: "Service Technician",
  [UserRole.SENIOR_TECHNICIAN]: "Senior Technician",
  [UserRole.INSTALLATION_TECHNICIAN]: "Installation Technician",
  [UserRole.APPRENTICE_TECHNICIAN]: "Apprentice Technician",
  [UserRole.ACCOUNTANT]: "Accountant",
  [UserRole.COLLECTION_OFFICER]: "Collection Officer",
  [UserRole.CASHIER]: "Cashier",
  [UserRole.PROCUREMENT_OFFICER]: "Procurement Officer",
  [UserRole.WAREHOUSE_OFFICER]: "Warehouse Officer",
  [UserRole.INVENTORY_CLERK]: "Inventory Clerk",
  [UserRole.CUSTOMER_CARE_AGENT]: "Customer Care Agent",
  [UserRole.DISPATCHER]: "Dispatcher",
  [UserRole.RECEPTIONIST]: "Receptionist",
  [UserRole.HR_OFFICER]: "HR Officer",
  [UserRole.QA_INSPECTOR]: "QA Inspector",
  [UserRole.SAFETY_OFFICER]: "Safety Officer",
  [UserRole.IT_SUPPORT]: "IT Support",
  [UserRole.DATA_ANALYST]: "Data Analyst",
  [UserRole.CUSTOMER]: "Customer",
};

export const EXECUTIVE_ROLES: UserRole[] = [
  UserRole.SUPER_ADMIN,
  UserRole.CHAIRMAN,
  UserRole.CEO,
  UserRole.COO,
  UserRole.CFO,
  UserRole.CTO,
  UserRole.CCO,
  UserRole.CIO,
];

export const BRANCH_LEADERSHIP: UserRole[] = [
  ...EXECUTIVE_ROLES,
  UserRole.REGIONAL_DIRECTOR,
  UserRole.BRANCH_MANAGER,
  UserRole.DEPUTY_BRANCH_MANAGER,
];

export const DEPT_HEADS: UserRole[] = [
  UserRole.HEAD_OF_SALES,
  UserRole.HEAD_OF_SERVICE,
  UserRole.HEAD_OF_INSTALLATION,
  UserRole.HEAD_OF_FINANCE,
  UserRole.HEAD_OF_COLLECTION,
  UserRole.HEAD_OF_PROCUREMENT,
  UserRole.HEAD_OF_WAREHOUSE,
  UserRole.HEAD_OF_HR,
  UserRole.HEAD_OF_CUSTOMER_CARE,
  UserRole.HEAD_OF_QUALITY,
  UserRole.HEAD_OF_IT,
  UserRole.HEAD_OF_MARKETING,
];

export const TECHNICIAN_ROLES: UserRole[] = [
  UserRole.SERVICE_TECHNICIAN,
  UserRole.SENIOR_TECHNICIAN,
  UserRole.INSTALLATION_TECHNICIAN,
  UserRole.APPRENTICE_TECHNICIAN,
];

export const SALES_ROLES: UserRole[] = [
  UserRole.HEAD_OF_SALES,
  UserRole.SALES_MANAGER,
  UserRole.SALES_TEAM_LEADER,
  UserRole.SALES_EXECUTIVE,
  UserRole.SALES_ENGINEER,
  UserRole.ACCOUNT_MANAGER,
];

export const COLLECTION_ROLES: UserRole[] = [
  UserRole.HEAD_OF_COLLECTION,
  UserRole.COLLECTION_MANAGER,
  UserRole.COLLECTION_SUPERVISOR,
  UserRole.COLLECTION_OFFICER,
];

export function isExecutive(role: UserRole): boolean {
  return EXECUTIVE_ROLES.includes(role);
}

export function isTechnician(role: UserRole): boolean {
  return TECHNICIAN_ROLES.includes(role);
}

export function isCustomer(role: UserRole): boolean {
  return role === UserRole.CUSTOMER;
}
